module CyelPostLicence {

	enum EnumDecision {valide, nonValide, refusee, acceptee, listeAttente, vide};
	enum EnumReponse {oui, ouiMais, non, nonMais, vide};
	enum EnumOrdre {un, deux, trois, quatre, cinq, vide};
	
	exception ResponsableInconnu{
		long id;
		string raison;
	};
	
	struct Licence{
		long numLicence;
		string nomLicence;
	};
	
	typedef sequence<Licence> ListeLicences;
	
	struct Academie{
		long numAcademie;
		string nomAcademie;
	};
	
	typedef sequence<Academie> ListeAcademies;
	
	struct Universite{
		long numUniv;
		string nomUniv;
		Academie academie;
	};
	
	typedef sequence<Universite> ListeUniversites;
		
	struct Etudiant{
		long INE;
		string nom;
		string prenom;
		Licence licence;
		Universite universite;
	};
		
	struct Candidature{
		Etudiant etudiant;
		long numUniversite;
		long numMaster;
		long classement;
	};
	
	typedef sequence<Candidature> ListeCandidatures;
	typedef sequence<Etudiant> ListeEtudiants;

	struct Master{
		long numMaster;
		string nomMaster;
	};
	
	typedef sequence<Master> ListeMaster;
	
	struct Accreditation{
		Universite universite;
		Master master;
	};

	struct Decision{
		Etudiant etudiant;
		long numUniversite;
		long numMaster;
		EnumDecision decision;
	};

	
	struct Voeu{
		long numVoeu;
		Universite universite;
		Master master;
		EnumOrdre ordre;
		EnumDecision etatCandidature;
		EnumReponse reponse;
		long numLicence;
	};
	
	typedef sequence<Voeu> ListeVoeux;

	struct Note{
		long INE;
		long semestre;
		long numSemestre;
		long moyenne;
		string obtention;
		string position;
		Licence licence;
		long numUniversite;		 
	};
	
	typedef sequence<Note> ListeNotes;

	exception EtudiantInconnu{
		long id;
		string raison;
	};
	
	exception AcademieIncorrecte{
		long id;
		string raison;
	};
	

	interface GestionnaireVoeux;
	interface GestionnaireCandidatures;
	typedef sequence<GestionnaireVoeux> ListeGestionnairesVoeux;
	typedef sequence<GestionnaireCandidatures> ListeGestionnairesCandidatures;
		
	interface GestionnaireAcces {
		readonly attribute ListeGestionnairesVoeux listeGestionnairesVoeux;
		readonly attribute ListeGestionnairesCandidatures ListeGestionnairesCandidatures;
		Etudiant identification(in long INE, in Academie academie) raises (EtudiantInconnu, AcademieIncorrecte);
		GestionnaireVoeux obtenirGestionnaireVoeux(in long numAcademie);
		GestionnaireCandidatures obtenirGestionnaireCandidatures(in long numUniversite);
		GestionnaireVoeux identificationUniv(in string login, in string password, in long numAcademie) raises (ResponsableInconnu);
		void inscriptionGestionnaireVoeux(in GestionnaireVoeux gestVoeux);
		void inscriptionGestionnaireCandidatures(in GestionnaireCandidatures gestCandidatures);
		
		Etudiant obtenirEtudiant(in long INE);
	};
	
	interface GestionnaireReferentiel {
		readonly attribute ListeAcademies listeAcademies;
		readonly attribute ListeMaster listeMasters;
		readonly attribute ListeLicences listeLicences;
	};
	
	interface GestionnaireCandidatures {
		attribute Universite universite;
		readonly attribute ListeMaster listeMaster;
		ListeNotes recupererListeNotes(in long INE, in boolean externe);
		void RAZPeriode();
		EnumDecision validerCandidature(in long numMaster, in long numLicence);
		void enregistrerCandidatures(in Etudiant etudiant, in long numMaster);
		ListeCandidatures consulterCandidatures(in long numMaster, in long numUniversite);
		void enregistrerClassement(in long INE, in long classement);
		void finPeriodeDecision();
		void majListe(in long INE, in Voeu voeu);
	};
	
	interface GestionnaireVoeux {
		attribute Academie academie;
		attribute long periode;
		readonly attribute ListeUniversites listeUniversite;
		ListeUniversites consulterAcreditations(in long numMaster, in boolean externe);
		void enregistrerVoeux(in Etudiant etudiant, in ListeVoeux listeVoeux);
		void repondreVoeu(in long INE, in Voeu voeu);
		ListeVoeux consulterVoeux(in long INE, in boolean externe);
		void cloturerPeriode();
		void RAZPeriode();
		ListeEtudiants recupererListeCandidatures(in long numMaster, in long numUniversite);
		void enregistrerDecision(in Decision decision);
		void supprimerVoeux(in long numVoeu);
	};
};