/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Client.ClientResponsable;
import CyelPostLicence.Etudiant;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cy
 */
public class AccueilResponsableFormation extends javax.swing.JFrame {
    
    private ClientResponsable client;
    private int clik = 0;

    /**
     * Creates new form AccueilResponsableFormation
     */
    public AccueilResponsableFormation() {
        initComponents();
    }

    AccueilResponsableFormation(ClientResponsable client) {
        initComponents();
        this.client = client;
        int periode = this.client.getPeriode();
        if(periode == 1 || periode > 2)
        {
            this.bt_recupererLesCandidatures.setEnabled(false);
        }
        if(periode == 2)
        {
            this.bt_recupererLesCandidatures.setEnabled(true);
        }
        
        initTableauCand();
       
    }
    
    // Constructeur bloqué ou non le bouton "Recuperer les candidatures"
    // Bouton actif des periode 2, des que click une fois dessus alors toujours inactif = 0
    AccueilResponsableFormation(ClientResponsable client, int click) {
        initComponents();
        this.client = client;
        int periode = this.client.getPeriode();
        if(periode == 1 || periode > 2 || click == 0)
        {
            this.bt_recupererLesCandidatures.setEnabled(false);
        }
        if(periode == 2 && click != 0)
        {
            this.bt_recupererLesCandidatures.setEnabled(true);
        }
        
        initTableauCand();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_candidatures = new javax.swing.JTable();
        bt_consulterNotes = new javax.swing.JButton();
        bt_choixCandidat = new javax.swing.JButton();
        bt_classerListeAttente = new javax.swing.JButton();
        bt_recupererLesCandidatures = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Accueil Responsable Formation");

        jLabel3.setText("Liste des demandes du Master");

        jTable_candidatures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom Prenom", "Licence provenance", "Universite provenance", "Etat"
            }
        ));
        jScrollPane1.setViewportView(jTable_candidatures);

        bt_consulterNotes.setText("Consulter Notes Candidat");
        bt_consulterNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consulterNotesActionPerformed(evt);
            }
        });

        bt_choixCandidat.setText("Admission candidat");

        bt_classerListeAttente.setText("Classer la liste d'attente");

        bt_recupererLesCandidatures.setText("Récupérer les candidatures");
        bt_recupererLesCandidatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_recupererLesCandidaturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_consulterNotes)
                        .addGap(34, 34, 34)
                        .addComponent(bt_choixCandidat)
                        .addGap(28, 28, 28)
                        .addComponent(bt_classerListeAttente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(bt_recupererLesCandidatures, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_recupererLesCandidatures)
                    .addComponent(bt_consulterNotes)
                    .addComponent(bt_choixCandidat)
                    .addComponent(bt_classerListeAttente))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_recupererLesCandidaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_recupererLesCandidaturesActionPerformed
        clik = 1;
        client.recupererLesCandidatures();
        AccueilResponsableFormation acc = new AccueilResponsableFormation(client,0);
        this.setVisible(false);
        acc.setVisible(true);
    }//GEN-LAST:event_bt_recupererLesCandidaturesActionPerformed

    private void bt_consulterNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consulterNotesActionPerformed
        int selectedRow = jTable_candidatures.getSelectedRow();
        if (selectedRow != -1) {
            String sINE = jTable_candidatures.getValueAt(selectedRow,0).toString();
            int INE = Integer.parseInt(sINE);

            ConsulterNotesCandidat notes = new ConsulterNotesCandidat(client,INE);
            this.setVisible(false);
            notes.setVisible(true);
        }
    }//GEN-LAST:event_bt_consulterNotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilResponsableFormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilResponsableFormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilResponsableFormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilResponsableFormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilResponsableFormation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_choixCandidat;
    private javax.swing.JButton bt_classerListeAttente;
    private javax.swing.JButton bt_consulterNotes;
    private javax.swing.JButton bt_recupererLesCandidatures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_candidatures;
    // End of variables declaration//GEN-END:variables

    private void initTableauCand() {
        Etudiant[] tabEtudiant;
        tabEtudiant = client.mesCandidatures();
        if(tabEtudiant != null)
        {
            DefaultTableModel model = new DefaultTableModel();
            //On renseigne les identifiants des colonnes dans le modèle
            model.setColumnIdentifiers(new String[]{ "NumINE","Nom etudiant","Prenom Etudiant", "Numero Licence","Licence Provenance", "Numero Université",  "Université Provenance", "Numero Academie", "Academie Provenance"});

            //On ajoute les ligne contenant les données dans le modèle
            for (Etudiant e : tabEtudiant) {
                model.addRow(new Object[]{e.INE, e.nom, e.prenom, e.licence.numLicence, e.licence.nomLicence, e.universite.numUniv,e.universite.nomUniv, e.universite.academie.numAcademie, e.universite.academie.nomAcademie});
            }

            //On ajoute le modèle dans la Jtable
            jTable_candidatures.setModel(model);
            jTable_candidatures.setEnabled(true);
        }
        
            
    }
}
