/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Client.ClientEtudiant;
import CyelPostLicence.Academie;
import CyelPostLicence.EnumDecision;
import CyelPostLicence.EnumOrdre;
import CyelPostLicence.EnumReponse;
import CyelPostLicence.Master;
import CyelPostLicence.Universite;
import CyelPostLicence.Voeu;
import Outils.Item;
import javax.swing.JFrame;

/**
 *
 * @author Cy
 */
public class AjouterVoeu_Universite extends javax.swing.JFrame {

    private ClientEtudiant client;
    private Master master;
    private Universite[] listeUniversite;
    private Voeu[] tabVoeu;

    /**
     * Creates new form AjouterVoeu_Universite
     */
    public AjouterVoeu_Universite() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public AjouterVoeu_Universite(ClientEtudiant client) {
        initComponents();
        this.client = client;
        this.setVisible(true);
    }

    public AjouterVoeu_Universite(ClientEtudiant client, Master master, Universite[] listeUniversite) {
        initComponents();
        this.client = client;
        this.master = master;
        this.listeUniversite = listeUniversite;
        lb_masterChoisi.setText(master.nomMaster);
        initcb_ListeUniversites();
        this.setVisible(true);
    }

    public void initcb_ListeUniversites() {
        cb_listeUniversites.removeAllItems();
        for (int i = 0; i < listeUniversite.length; i++) {
            cb_listeUniversites.addItem(new Item(listeUniversite[i].numUniv, listeUniversite[i].nomUniv));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_listeUniversites = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lb_masterChoisi = new javax.swing.JLabel();
        bt_enregistrerVoeu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ajouter un Voeu");

        jLabel2.setText("Choisir l'universite");

        jLabel3.setText("Diplome choisi :");

        lb_masterChoisi.setText("jLabel4");

        bt_enregistrerVoeu.setText("Enregistrer son choix");
        bt_enregistrerVoeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerVoeuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_masterChoisi))
                            .addComponent(cb_listeUniversites, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_enregistrerVoeu)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_masterChoisi))
                .addGap(27, 27, 27)
                .addComponent(cb_listeUniversites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(bt_enregistrerVoeu)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_enregistrerVoeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerVoeuActionPerformed
        boolean doublon = false;
        tabVoeu = client.mesVoeux();
        Item selectItem = (Item) cb_listeUniversites.getSelectedItem();
        Academie academie = getAcademie(selectItem.getId());
        Universite u = new Universite(selectItem.getId(), selectItem.getValeur(), academie);
        Voeu listeV[] = new Voeu[1];
        for (int i = 0; i < tabVoeu.length; i++) {
            if ((tabVoeu[i].universite.numUniv == u.numUniv) && (tabVoeu[i].master.numMaster == master.numMaster)) {
                doublon = true;
            }
        }

        if (doublon) {
            new PopUpErreur().setVisible(true);
            this.dispose();
        } else {
            listeV[0] = new Voeu(0, u, master, EnumOrdre.vide, EnumDecision.vide, EnumReponse.vide, client.monEtudiant.licence.numLicence);
            client.enregistrerVoeux(listeV);
            this.dispose();
        }

        
    }//GEN-LAST:event_bt_enregistrerVoeuActionPerformed

    public Academie getAcademie(int numeroUniv) {
        Academie a = null;

        for (int i = 0; i < listeUniversite.length; i++) {
            if (listeUniversite[i].numUniv == numeroUniv) {
                a = listeUniversite[i].academie;
            }
        }

        return a;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterVoeu_Universite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterVoeu_Universite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterVoeu_Universite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterVoeu_Universite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterVoeu_Universite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_enregistrerVoeu;
    private javax.swing.JComboBox cb_listeUniversites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_masterChoisi;
    // End of variables declaration//GEN-END:variables
}
