/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package IHM;

import Client.ClientMinistere;

/**
 *
 * @author Cy
 */
public class InterfaceMinistere extends javax.swing.JFrame {
    
    public static ClientMinistere client;
    public static int periode;

    /**
     * Creates new form InterfaceMinistere
     */
    public InterfaceMinistere() {
        initComponents();
        //lb_periode.setText("Periode "+Integer.toString(periode));
    }
    
    public InterfaceMinistere(ClientMinistere client) {
        this.client = client;
        initComponents();
        this.setVisible(true);
        this.periode = client.periode();
        bt_actualiserListes.setEnabled(false);
        lb_periode.setText("Periode "+Integer.toString(periode));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_cloturerPeriode = new javax.swing.JButton();
        bt_RAZ = new javax.swing.JButton();
        bt_actualiserListes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_periode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_cloturerPeriode.setBackground(new java.awt.Color(255, 0, 0));
        bt_cloturerPeriode.setText("Cloturer la periode");
        bt_cloturerPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cloturerPeriodeActionPerformed(evt);
            }
        });

        bt_RAZ.setBackground(new java.awt.Color(255, 204, 0));
        bt_RAZ.setText("RAZ la periode");
        bt_RAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RAZActionPerformed(evt);
            }
        });

        bt_actualiserListes.setBackground(new java.awt.Color(0, 102, 255));
        bt_actualiserListes.setText("Actualiser les listes (période 4)");
        bt_actualiserListes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualiserListesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ministère");

        lb_periode.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cloturerPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_RAZ, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(bt_actualiserListes, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lb_periode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_periode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_actualiserListes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cloturerPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bt_RAZ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cloturerPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cloturerPeriodeActionPerformed
        if (periode < 4) {
            periode++;
        }
        client.cloturerPeriode();
        if (periode == 4) {
            bt_actualiserListes.setEnabled(true);
        }
        else {
            bt_actualiserListes.setEnabled(false);
        }
        lb_periode.setText("Periode "+Integer.toString(periode));
    }//GEN-LAST:event_bt_cloturerPeriodeActionPerformed

    private void bt_RAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RAZActionPerformed
        periode = 1;
        client.RAZPeriode();
        lb_periode.setText("Periode "+Integer.toString(periode));
    }//GEN-LAST:event_bt_RAZActionPerformed

    private void bt_actualiserListesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualiserListesActionPerformed
        client.actualiserListes();
    }//GEN-LAST:event_bt_actualiserListesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMinistere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMinistere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMinistere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMinistere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                client = new ClientMinistere(args);
                new InterfaceMinistere(client);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_RAZ;
    private javax.swing.JButton bt_actualiserListes;
    private javax.swing.JButton bt_cloturerPeriode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_periode;
    // End of variables declaration//GEN-END:variables
}
